/*
 Author:     Alice, Du Weichao
 Date:       24 Jan 2017
 Problem:    Find the Difference
 Difficulty: Easy
 Source:     https://leetcode.com/problems/find-the-difference/
 Notes:
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/


public class Solution {
    public char findTheDifference(String s, String t) {
        for(int i = 0; i < s.length(); i ++)
            t = t.replaceFirst(Character.toString(s.charAt(i)),"");
            
        return t.charAt(0);
    }
}
